### Numpy Basic
#### 배열생성

In [ ]:
import numpy as np
# 1차원 배열 생성
a = np.array([1, 2, 3, 4])

# 2차원 배열 생성
b = np.array([[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]])

# 3차원 배열 생성
c = np.array([[[ 0, 1, 2, 3],
           [ 4, 5, 6, 7],
           [ 8, 9, 10, 11]]])

### Numpy Array 속성
- ndim : ndarray의 차원을 나타냄
- shape : 각 차원의 ndarray 크기를 튜플 형태로 나타냄
- size : ndarray에있는 요소의 총 수
- dtype : ndarray의데이터 유형
   - uint8 ~ uint64, int8 ~ int64, float16 ~ float128, bool 등
- T : ndarray의 전치된 결과 반환 (행열 바꾸기)

In [ ]:
### Numpy Array 속성
x = np.array([[1,2,3], [4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
print(x.ndim)
print(x.shape)
print(x.size)
print(x.dtype)

2
(2, 3)
6
int64


# Numpy Indexing
- 특정행과 열에 접근: 넘파이배열[행, 열]
- :슬라이싱도 가능

In [ ]:
### Numpy Array 접근 -> [행, 열]
x[0, 1]

2

In [ ]:
x[1, 2]

6

In [ ]:
x[:, 1:]

array([[2, 3],
       [5, 6]])

##### 배열생성함수
- arange 수의 범위를 만들어주는 함수
- linspace 수의 범위를 균일하게 나누고자 할 때 사용
- np.ones((행,열))   1로 채워진 배열생성
- np.zeros((행,열))  0으로 채워진 배열생성
- np.full((행,열), 값) 특정값으로 채워진 배열생성

In [ ]:
# 0 ~ 9 까지 값을 갖는 배열
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# 0.1 ~ 1.0 까지 0.1씩 증가는 값을 갖는 배열 생성
np.arange(0, 1, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [ ]:
np.linspace(1, 10, 3)

array([ 1. ,  5.5, 10. ])

In [ ]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [ ]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [ ]:
np.full((2,2), -1)

array([[-1, -1],
       [-1, -1]])

##### RandomSampling

In [ ]:
import numpy as np
np.random.seed(0)   #

a = np.arange(100)
a
# np.random.choice(a, size=10, replace=False)  #비복원추출
np.random.choice(a, size=10, replace=True)  #복원추출

array([44, 47, 64, 67, 67,  9, 83, 21, 36, 87])

In [ ]:
# 연습문제
# 동전던지기
a = np.arange(2)
a
# 10회 수행
np.random.choice(a, size=10, replace=True)

array([1, 0, 1, 0, 0, 1, 1, 0, 1, 0])

#### 난수생성방법
- np.random.rand : 0부터 1사이의 균일분포
- np.random.randn : 가우시안 표준 정규 분포
- np.random.randint : 균일 분포의 정수 난수

In [ ]:
np.random.randint(0, 100, 33)

array([55, 28, 34,  0,  0, 36, 53,  5, 38, 17, 79,  4, 42, 58, 31,  1, 65,
       41, 57, 35, 11, 46, 82, 91,  0, 14, 99, 53, 12, 42, 84, 75, 68])

In [ ]:
np.random.randn(3,4)

array([[ 0.11495917,  0.34531264, -1.73495876,  1.65835111],
       [ 2.29977152, -0.47113526,  1.26271548, -1.17051545],
       [ 1.0657892 , -0.69993739,  0.14407911,  0.3985421 ]])

In [ ]:
np.random.randint(1,100,5)

array([67, 53, 68, 62, 15])

In [ ]:
# 로또 번호 추출 1-45 중 6개

np.random.randint(1,46,6)

array([18, 28, 15, 42,  2, 37])